name: AncapStates
main: states.Main.AncapStates
version: beta-2.3-SNAPSHOT.1
api-version: 1.16

depend:
  - AncapLibrary

softdepend:
  - dynmap

commands:
  city:
    description:
    permission:
    usage: "Usage: /<command>"
    aliases: [c]
  nation:
    description:
    permission:
    usage: "Usage: /<command>"
    aliases: [n]
  war:
    description:
    permission:
    usage: "Usage: /<command>"
  ancapstates:
    description:
    permission:
    usage: "Usage: /<command>"
    aliases: [as]
  castle:
    description:
    permission:
    usage: "Usage: /<command>"
  test:
    description:
    permission:
    usage: "Usage: /<command>"
  player:
    description:
    permission:
    usage: "Usage: /<command>"
  here:
    description:
    permission:
    usage: "Usage: /<command>"
  migration:
    description:
    permission:
    usage: "Usage: /<command>"