name: AncapStates
main: states.Main.AncapStates
version: beta.2.3-SNAPSHOT.2-alpha.1.2
api-version: 1.16

depend:
  - AncapLibrary

softdepend:
  - dynmap

commands:
  city:
    description:
    permission:
    usage: "Usage: /<command>"
    aliases: [c]
  nation:
    description:
    permission:
    usage: "Usage: /<command>"
    aliases: [n]
  ancapstates:
    description:
    permission:
    usage: "Usage: /<command>"
    aliases: [as]
  test:
    description:
    permission:
    usage: "Usage: /<command>"
  player:
    description:
    permission:
    usage: "Usage: /<command>"
  here:
    description:
    permission:
    usage: "Usage: /<command>"
  migration:
    description:
    permission:
    usage: "Usage: /<command>"