name: AncapStates
main: states.States.AncapStates
version: beta 1.0
api-version: 1.16

softdepend:
  - dynmap

commands:
  city:
    description:
    permission:
    usage: "Usage: /<command>"
    aliases: [c]
  nation:
    description:
    permission:
    usage: "Usage: /<command>"
    aliases: [n]
  war:
    description:
    permission:
    usage: "Usage: /<command>"
  ancapstates:
    description:
    permission:
    usage: "Usage: /<command>"
    aliases: [as]
  castle:
    description:
    permission:
    usage: "Usage: /<command>"
  test:
    description:
    permission:
    usage: "Usage: /<command>"
  player:
    description:
    permission:
    usage: "Usage: /<command>"
  here:
    description:
    permission:
    usage: "Usage: /<command>"
  migration:
    description:
    permission:
    usage: "Usage: /<command>"